# Generated by Django 3.2.5 on 2022-09-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_img'),
        ),
        migrations.AlterField(
            model_name='reviewpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews_img'),
        ),
    ]
